### ISSUE TITLE
Matrix multiplication

### ISSUE THREAD

**Issue by phulehai** [CMU-MS-DAS-Modern-Programming-Mini/fall2022-homework-1#1]
Hi Ivan
For matrix multiplication, do we need to consider empty matrices?
Thanks in advance.
Phu

**Comment by icaoberg** [comment]
The homework is asking to return True/False depending on whether these can be multiplied.

Multiplying an empty matrix against any other should, for the purpose of the homework return False. So yes, I would advise testing it.

**Comment by khionech** [comment]
Hi Ivan,

I am a little confused after seeing your response in the repo:

1. I would like to clarify what is matrix multiplication here in the question. Is it:
(a) [apply the * operator on two Numpy arrays](https://numpy.org/doc/stable/reference/generated/numpy.multiply.html) 
or
(b) [the inner product of two Numpy arrays](https://numpy.org/doc/stable/reference/generated/numpy.dot.html) ([definition on Wikipedia](https://en.wikipedia.org/wiki/Matrix_multiplication))

2. You mentioned that "Multiplying an empty matrix against any other should return False" but how about multiplying an empty matrix against another empty matrix? In both (a) and (b) situations, an empty matrix cannot be multiplied against any other matrix but can be multiplied against an empty matrix!

Thank you!
